using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Wakeel.Application.DTOs.Chat;

/// <summary>
/// The response envelope returned to the client after POST /api/chat/ask.
/// chat_id and created_at are generated by .NET.
/// reply and conversation_id are translated from the Node.js AI service response.
/// </summary>
public record AskChatResponse
{
    /// <summary>A unique ID for this specific chat message, generated by .NET.</summary>
    [JsonPropertyName("chat_id")]
    public Guid ChatId { get; init; }

    /// <summary>The conversation thread ID (generated or reused by .NET).</summary>
    [JsonPropertyName("conversation_id")]
    public string ConversationId { get; init; } = string.Empty;

    /// <summary>The AI assistant's reply text.</summary>
    [JsonPropertyName("reply")]
    public string Reply { get; init; } = string.Empty;

    /// <summary>List of knowledge sources cited in the reply.</summary>
    [JsonPropertyName("sources")]
    public List<string> Sources { get; init; } = new();

    /// <summary>
    /// Fields the AI still needs to collect to complete a multi-step action.
    /// Null if the AI's reply is complete.
    /// </summary>
    [JsonPropertyName("missing_fields")]
    public object? MissingFields { get; init; }

    /// <summary>
    /// A structured result card (calculation, document_draft, or leave_draft).
    /// Null if the reply is a plain text response.
    /// </summary>
    [JsonPropertyName("result_card")]
    public object? ResultCard { get; init; }

    /// <summary>The UTC timestamp at which .NET received and processed this message.</summary>
    [JsonPropertyName("created_at")]
    public DateTime CreatedAt { get; init; }
}
