using System;

namespace Wakeel.Domain.Entities;

/// <summary>
/// Represents a document generated by the AI for a specific employee.
/// </summary>
public class GeneratedDocument
{
    public Guid Id { get; set; }
    public Guid CompanyId { get; set; }
    public Guid? EmployeeId { get; set; }
    public Guid? TemplateId { get; set; }
    public Guid? GeneratedByUserId { get; set; }

    public string DocumentType { get; set; } = string.Empty;
    public string Title { get; set; } = string.Empty;
    public string Content { get; set; } = string.Empty;
    public string Status { get; set; } = "Draft";
    
    public string? PdfUrl { get; set; }
    public string? EmailSentTo { get; set; }
    public DateTime? EmailSentAt { get; set; }
    public DateTime? FinalizedAt { get; set; }
    
    public DateTime CreatedAt { get; set; }
    public DateTime UpdatedAt { get; set; }
    
    // Navigation properties
    public Company Company { get; set; } = null!;
    public EmployeeProfile? Employee { get; set; }
    public DocumentTemplate? Template { get; set; }
    public User? GeneratedByUser { get; set; }
}
