name: Build, Publish and Deploy to MonsterASP.NET

on:
  push:
    branches:
      - develop

jobs:
  build_and_deploy:
    runs-on: windows-latest

    defaults:
      run:
        working-directory: ./WakeelAI

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Restore packages
        run: dotnet restore WakeelAI.slnx

      - name: Build
        run: dotnet build WakeelAI.slnx --configuration Release --no-restore

      - name: Run tests
        run: dotnet test WakeelAI.slnx --configuration Release --no-build
        continue-on-error: true

      - name: Publish API
        run: |
          dotnet publish ./Wakeel.API/Wakeel.API.csproj `
            --configuration Release `
            --no-build `
            --output ../publish

      - name: Deploy
        uses: rasmusbuchholdt/simply-web-deploy@2.1.0
        with:
          website-name: ${{ secrets.WEBSITE_NAME }}
          server-computer-name: ${{ secrets.SERVER_COMPUTER_NAME }}
          server-username: ${{ secrets.SERVER_USERNAME }}
          server-password: ${{ secrets.SERVER_PASSWORD }}
          source-path: publish